### ISSUE TITLE
Other Data Sets

### ISSUE THREAD

**Issue by jkassis** [marcusklasson/GroceryStoreDataset#1]
Hi Marcus.

Thanks for posting this. Do you know of other similar datasets?

**Comment by bilelsgh** [comment]
Hello, 

Does someone have tried to use this dataset in a CNN ? Did you get good performances ?

**Comment by RazanMohamed** [comment]
Is this a benchmark dataset?

**Comment by marcusklasson** [comment]
Sorry for the great delay on related works. For other similar food datasets that I am aware of, I would refer to 

- Our follow-up paper (Patterns 2020) in the section called "Food Datasets": https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=18357764652748957056 
- This nice TPAMI survey paper on Fine-grained image recognition and datasets: https://arxiv.org/abs/2111.06119 

Closing this issue.
